databases:
  - name: tons_db
    databaseName: tons_db
    user: user
    plan: free

services:
  - type: web
    name: tons-game-hub
    runtime: python
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommorce.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tons_db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"